apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uri.work.gd-certificate
spec:
  secretName: uri.work.gd-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - uri.work.gd