apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.17.1
      helm:
        releaseName: cert-manager
      valuesObject:
        installCRDs: true
    - repoURL: https://github.com/UriZafrir/oracle-cloud-jellyfin.git
      targetRevision: HEAD
      path: gitops/extras/cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
