apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    helm:
      releaseName: ingress-nginx
      valuesObject:
        # controller:
        #   service:
        #     type: NodePort
        controller:
          service:
            externalIPs: 129.159.142.131
        # hostPort:
        #   # -- Enable 'hostPort' or not
        #   enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

