apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://utkuozdemir.org/helm-charts
      chart: jellyfin
      targetRevision: 2.0.0
      helm:
        releaseName: jellyfin
        valuesObject:
          image:
            repository: docker.io/jellyfin/jellyfin
            tag: 10.10.6-arm64.20250216-215628
          service:
            type: NodePort
          persistence:
            data:
              # enabled: true
              # storageClass: local-path
              # size: 20Gi
              enabled: true
              isPvc: false
              customVolume:
                hostPath:
                  path: /opt/jellyfin-data
          hostPort:
            # -- Use host port for the application
            enabled: true
            # -- Host port to bind to
            port: 8096
          additionalPorts:
            - name: tcp-8920
              containerPort: 8920
              protocol: TCP
              hostPort: 8920
          additionalServicePorts:
            - name: tcp-8920
              port: 8920
              targetPort: 8920
              protocol: TCP
          # podSecurityContext:
          #   runAsUser: 1000
          #   runAsGroup: 1000
          #   fsGroup: 1000
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
