apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: plex
    repoURL: https://utkuozdemir.org/helm-charts
    targetRevision: 2.1.1
    helm:
      releaseName: plex
      valuesObject:
        # image:
        #   repository: lscr.io/linuxserver/plex
        #   tag: latest
        service:
          type: NodePort 
        persistence:
          data: 
            enabled: true
            isPvc: false
            customVolume:
              hostPath:
                path: /opt/jellyfin-data
        
  destination:
    server: "https://kubernetes.default.svc"
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

